/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.TourSave = factory(root.ApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The TourSave model module.
   * @module model/TourSave
   * @version 1.0
   */

  /**
   * Constructs a new <code>TourSave</code>.
   * @alias module:model/TourSave
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>TourSave</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TourSave} obj Optional instance to populate.
   * @return {module:model/TourSave} The populated <code>TourSave</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('nickname'))
        obj.nickname = ApiClient.convertToType(data['nickname'], 'String');
      if (data.hasOwnProperty('tourContent'))
        obj.tourContent = ApiClient.convertToType(data['tourContent'], 'String');
      if (data.hasOwnProperty('tourEndDate'))
        obj.tourEndDate = ApiClient.convertToType(data['tourEndDate'], 'String');
      if (data.hasOwnProperty('tourLocation'))
        obj.tourLocation = ApiClient.convertToType(data['tourLocation'], 'String');
      if (data.hasOwnProperty('tourNeed'))
        obj.tourNeed = ApiClient.convertToType(data['tourNeed'], 'String');
      if (data.hasOwnProperty('tourStartDate'))
        obj.tourStartDate = ApiClient.convertToType(data['tourStartDate'], 'String');
      if (data.hasOwnProperty('tourTeam'))
        obj.tourTeam = ApiClient.convertToType(data['tourTeam'], 'String');
      if (data.hasOwnProperty('tourTitle'))
        obj.tourTitle = ApiClient.convertToType(data['tourTitle'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} nickname
   */
  exports.prototype.nickname = undefined;

  /**
   * @member {String} tourContent
   */
  exports.prototype.tourContent = undefined;

  /**
   * @member {String} tourEndDate
   */
  exports.prototype.tourEndDate = undefined;

  /**
   * @member {String} tourLocation
   */
  exports.prototype.tourLocation = undefined;

  /**
   * @member {String} tourNeed
   */
  exports.prototype.tourNeed = undefined;

  /**
   * @member {String} tourStartDate
   */
  exports.prototype.tourStartDate = undefined;

  /**
   * @member {String} tourTeam
   */
  exports.prototype.tourTeam = undefined;

  /**
   * @member {String} tourTitle
   */
  exports.prototype.tourTitle = undefined;


  return exports;

}));
